# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Feuerwehr Frielendorf
      path: homepage
      class: first
    - label: Einsätze
      path: operations
    - label: Unsere Wehren
      path: departments
      list:
          contenttype: departments
      class: last
    - label: Führung
      link: ''
      display_on_positions:
        - 0
      submenu:
        - label: GBI Norbert Mühling
          path: people/1
        - label: Stellv. GBI Michael Bühn
          path: people/2
        - label: Stellv. GBI Markus Schmerer
          path: people/3
    - label: Fachgruppen
      link: ''
      display_on_positions:
        - 0
      submenu:
        - label: Führungsstaffel
          path: page/fuehrungsstaffel
        - label: ArGe Atemschutz
          path: page/arge-atemschutz
    - label: Grußwort
      path: page/grusswort
      display_on_positions:
        - 0
    - label: Impressum
      path: page/Impressum
      display_on_positions:
        - 1
